MODEL <- "JD3_DfmModel"
MODELESTIMATION <- "JD3_SsfModelEstimation"

#' Create Dynamic Factor Model
#'
#' @param nfactors Integer. Number of factors.
#' @param nlags Integer. Number of lags in VAR.
#' @param factors_type Character vector. Respecting the order of the series in
#'   the input data, you must refer here the link between the (transformed)
#'   series and the factors. Three options are possible:
#'  \itemize{
#'    \item{"M"}{Variables expressed in terms of monthly growth rates can be
#'    linked to a factor representing the underlying monthly growth rate of the
#'    economy if "M" is selected}
#'    \item{"Q"}{Monthly or quarterly variables that are correlated with the the
#'    underlying quarterly growth rate of the economy can be linked to a
#'    weighted average of the factors representing the underlying monthly
#'    growth rate of the economy. Such a weighted average is meant to represent
#'    quarterly growth rates, and it is implemented by selecting "Q"}
#'    \item{"YoY"}{The variables can also be linked to the cumulative sum of the
#'    last 12 monthly factors. If the model is designed in such a way that the
#'    monthly factors represent monthly growth rates, the resulting cumulative
#'    sum boils down to the year-on-year growth rate. Thus, variables expressed
#'    in terms of year-on-year growth rates or surveys that are correlated with
#'    the year-on-year growth rates of the reference series should be linked to
#'    the factors using "YoY".}
#'  }
#' @param factors_loading Boolean matrix. It represents the factor loading
#'   structure. The dimension of the matrix should be 'number of series' x
#'   'number of factors'. For each row representing each series, the user must
#'   mention whether the corresponding factor load on this series.
#' @param var_init Character. The first unobserved factors values in the sample
#'   is assumed either to be equal to zero or be consistent with a normal
#'   distribution with mean zero and a variance consistent with the
#'   unconditional variance of the VAR. The latter is the default.
#' @param mVariance Not yet implemented. Keep it on NULL.
#' @return an object of class 'JD3_DfmModel'
#' @export
#'
#' @examples
#' dfm_model <- model(
#'     nfactors = 2,
#'     nlags = 2,
#'     factors_type = c("M", "M", "YoY", "M", "Q"),
#'     factors_loading = matrix(data = TRUE, 5, 2),
#'     var_init = "Unconditional"
#' )
#'
model <- function(nfactors, nlags, factors_type, factors_loading, var_init = c("Unconditional", "Zero"), mVariance = NULL) {
    var_init <- match.arg(var_init)

    jfactors_loading <- rjd3toolkit::.r2jd_matrix(factors_loading)
    jmodel <- .jcall(
        "jdplus/dfm/base/r/DynamicFactorModels",
        "Ljdplus/dfm/base/core/DynamicFactorModel;",
        "model",
        as.integer(nfactors),
        as.integer(nlags),
        .jarray(as.character(factors_type)),
        jfactors_loading,
        .jnew("java/lang/String", as.character(var_init)),
        .jnull("[D")
    )

    return(rjd3toolkit::.jd3_object(jmodel, MODEL))
}

#' Estimate DFM with Principal components Analysis
#'
#' @param dfmModel an object of class 'JD3_DfmModel'. Typically generated by the
#'   model() function.
#' @param data an mts object.
#' @param standardized Boolean. Indicate whether the input series were already
#'   standardized or not. Default is FALSE, i.e. not previously standardized
#' @param n_out Number of out-of-periods considered in the processing. Must be
#'   greater than the required number of forecasts asked in the forecasting
#'   funcions.
#' @return an object of class 'JD3_SsfModelEstimation'
#' @export
#'
#' @examples
#' set.seed(100)
#' data <- ts(matrix(rnorm(500), 100, 5), frequency = 12, start = c(2010, 1))
#' data[100, 1] <- data[99:100, 2] <- data[(1:100)[-seq(3, 100, 3)], 5] <- NA
#' dfm_model <- model(
#'     nfactors = 2,
#'     nlags = 2,
#'     factors_type = c("M", "M", "YoY", "M", "Q"),
#'     factors_loading = matrix(data = TRUE, 5, 2),
#'     var_init = "Unconditional"
#' )
#' rslt_pca <- estimate_pca(dfm_model, data)
#'
estimate_pca <- function(dfmModel, data, standardized = FALSE, n_out = 12) {
    freq <- frequency(data)
    start <- start(data)

    jdata <- rjd3toolkit::.r2jd_matrix(data)

    jpca <- .jcall(
        "jdplus/dfm/base/r/DynamicFactorModels",
        "Ljdplus/dfm/base/core/DfmResults;",
        "estimate_PCA",
        dfmModel$internal,
        jdata,
        as.integer(freq),
        .jarray(as.integer(start)),
        standardized,
        as.integer(n_out)
    )

    return(
        structure(
            list(
                series_names = colnames(data),
                start = start,
                freq = freq,
                jestimates = rjd3toolkit::.jd3_object(jpca, result = TRUE)
            ),
            class = MODELESTIMATION
        )
    )
}

#' Estimate DFM with Expectations-Maximization algorithm
#'
#' @param dfmModel an object of class 'JD3_DfmModel'. Typically generated by the
#'   model() function.
#' @param data an mts object.
#' @param standardized Boolean. Indicate whether the input series were already
#'   standardized or not. Default is FALSE, i.e. not previously standardized
#' @param n_out Number of out-of-periods considered in the processing. Must be
#'   greater than the required number of forecasts asked in the forecasting
#'   funcions.
#' @param pca_init Boolean. Indicate whether a principal components analysis
#'   is performed beforehand and used as an initial condition for the EM
#'   algorithm.
#' @param max_iter Integer. Maximum number of iterations of the EM algorithm.
#' @param eps Numeric. EM algorithm is run until the percentage likelihood does
#'   not increase by more than the eps value (1e-9 is the default) or until the
#'   maximum number of iterations is hit.
#' @return an object of class 'JD3_SsfModelEstimation'
#' @export
#'
#' @examples
#' set.seed(100)
#' data <- ts(matrix(rnorm(500), 100, 5), frequency = 12, start = c(2010, 1))
#' data[100, 1] <- data[99:100, 2] <- data[(1:100)[-seq(3, 100, 3)], 5] <- NA
#' dfm_model <- model(
#'     nfactors = 2,
#'     nlags = 2,
#'     factors_type = c("M", "M", "YoY", "M", "Q"),
#'     factors_loading = matrix(data = TRUE, 5, 2),
#'     var_init = "Unconditional"
#' )
#' rslt_em <- estimate_em(dfm_model, data)
#'
estimate_em <- function(dfmModel, data, standardized = FALSE, n_out = 12,
                        pca_init = TRUE, max_iter = 100, eps = 1e-9) {
    freq <- frequency(data)
    start <- start(data)

    jdata <- rjd3toolkit::.r2jd_matrix(data)

    jem <- .jcall(
        "jdplus/dfm/base/r/DynamicFactorModels",
        "Ljdplus/dfm/base/core/DfmResults;",
        "estimate_EM",
        dfmModel$internal,
        jdata,
        as.integer(freq),
        .jarray(as.integer(start)),
        standardized,
        as.integer(n_out),
        pca_init,
        as.integer(max_iter),
        as.numeric(eps)
    )

    return(
        structure(
            list(
                series_names = colnames(data),
                start = start,
                freq = freq,
                jestimates = rjd3toolkit::.jd3_object(jem, result = TRUE)
            ),
            class = MODELESTIMATION
        )
    )
}


#' Estimate DFM with Maximum Likelihood
#'
#' @param dfmModel an object of class 'JD3_DfmModel'. Typically generated by the
#'   model() function.
#' @param data an mts object.
#' @param standardized Boolean. Indicate whether the input series were already
#'   standardized or not. Default is FALSE, i.e. not previously standardized
#' @param n_out Number of out-of-periods considered in the processing. Must be
#'   greater than the required number of forecasts asked in the forecasting
#'   funcions.
#' @param pca_init Boolean. Indicate whether a principal components analysis is
#'   performed beforehand and used as an initial condition for the EM algorithm
#'   (if em_init=TRUE) or directly for the estimation by ML.
#' @param em_init Boolean. Indicate whether the EM algorithm is performed
#'   beforehand and used as an initial condition for the estimation by ML.
#' @param em_max_iter Integer. Maximum number of iterations of the EM algorithm.
#'   Ignored if em_init = FALSE.
#' @param em_eps Numeric. EM algorithm is run until the percentage likelihood
#'   does not increase by more than the eps value (1e-9 is the default) or until
#'   the maximum number of iterations is hit. Ignored if em_init = FALSE.
#' @param max_iter Integer. Maximum number of iterations for the ML estimation.
#' @param max_block_iter Integer. Maximum number of iterations in optimization
#'   by block. The model parameters are divided in two blocks: one related to
#'   the measurement equations and one to the VAR. While the EM algorithm
#'   requires one iteration per block, the numerical optimization allows us to
#'   set the number of iterations desired per block.
#' @param simpl_model_iter Integer. Number of simplified model iterations
#'   allowed.
#' @param independent_var_shocks Boolean. Whether we assume that shocks in the
#'   VAR block are independent.
#' @param mixedEstimation Boolean. The mixed estimation option alternates
#'   between the iterations for the VAR block alone and simultaneous iterations
#'   for the two blocks.
#' @param eps Numeric. ML estimation is run until the percentage likelihood does
#'   not increase by more than the eps value (1e-9 is the default) or until the
#'   maximum number of iterations is hit.
#' @return an object of class 'JD3_SsfModelEstimation'
#' @export
#'
#' @examples
#' set.seed(100)
#' data <- ts(matrix(rnorm(500), 100, 5), frequency = 12, start = c(2010, 1))
#' data[100, 1] <- data[99:100, 2] <- data[(1:100)[-seq(3, 100, 3)], 5] <- NA
#' dfm_model <- model(
#'     nfactors = 2,
#'     nlags = 2,
#'     factors_type = c("M", "M", "YoY", "M", "Q"),
#'     factors_loading = matrix(data = TRUE, 5, 2),
#'     var_init = "Unconditional"
#' )
#' rslt_ml <- estimate_ml(dfm_model, data)
#'
estimate_ml <- function(dfmModel, data, standardized = FALSE, n_out = 12,
                        pca_init = TRUE, em_init = TRUE, em_max_iter = 100,
                        em_eps = 1e-9, max_iter = 1000, max_block_iter = 5,
                        simpl_model_iter = 15, independent_var_shocks = FALSE,
                        mixedEstimation = TRUE, eps = 1e-9) {
    freq <- frequency(data)
    start <- start(data)

    jdata <- rjd3toolkit::.r2jd_matrix(data)

    jml <- .jcall(
        "jdplus/dfm/base/r/DynamicFactorModels",
        "Ljdplus/dfm/base/core/DfmResults;",
        "estimate_ML",
        dfmModel$internal,
        jdata,
        as.integer(freq),
        .jarray(as.integer(start)),
        standardized,
        as.integer(n_out),
        pca_init,
        em_init,
        as.integer(em_max_iter),
        as.numeric(em_eps),
        as.integer(max_iter),
        as.integer(max_block_iter),
        as.integer(simpl_model_iter),
        independent_var_shocks,
        mixedEstimation,
        as.numeric(eps)
    )

    return(
        structure(
            list(
                series_names = colnames(data),
                start = start,
                freq = freq,
                jestimates = rjd3toolkit::.jd3_object(jml, result = TRUE)
            ),
            class = MODELESTIMATION
        )
    )
}
